---
title:  |
        | Legislature Size and Welfare: Evidence from Brazil
author: Response to Reviewers
date: \today
fontsize: 12pt
margin: 2cm
urlcolor: darkblue
linkcolor: Mahogany
citecolor: Mahogany
spacing: single
papersize: a4paper
bibliography: ../article/references.bib
biblio-style: apalike
output:
  pdf_document:
    citation_package: natbib
    fig_caption: yes
    number_sections: no
    keep_tex: no
    toc: no
    toc_depth: 3
    template: memo-template.latex
    md_extensions: +raw_attribute
---

\noindent Dear Editors and Reviewers,
\vspace{.5cm}

\noindent We would like to thank you all for the opportunity to revise our
manuscript, "Legislature Size and Welfare: Evidence from Brazil" (Ms. No.
AJPS-44979). We have made several revisions to the paper along the lines
suggested by the Editors and Reviewers and we believe the manuscript has
improved significantly as a result. 

Following Reviewers 1 and 2, we have incorporated additional literature into
the manuscript, which has given the paper a clearer theoretical framework
through which our results can be interpreted. We have also discussed the scope
conditions of our findings in further detail and included a new paragraph
explaining why newly-elected councilors tend to join pro-mayor coalitions, thus
addressing two important concerns raised by Reviewer 3. We believe these
changes have made the paper clearer and more comprehensive.

In response to comments from Reviewer 1, we have revised our Methods section to
clarify our selection of independent variables, particularly the use of
covariates to improve the efficiency and consistency of our estimates. Moreover,
we have also added a new section in the Supplemental Materials to explain how we
conducted our survey and how it contributes to our results. We believe these
additions also give the paper a better theoretical frame to help readers sort
through the results we present.

Below we discuss in more detail these changes and the several others we have
made to the manuscript in response to comments from the Editors, the Reviewers,
and the Editorial Office. We thank the Editors again for the opportunity to
revise the manuscript, and the Reviewers for their extremely helpful comments.

\vspace{.5cm}
\noindent Sincerely,

\vspace{.2cm}
\noindent The Authors

# Reviewer 1 Comments and Responses

\noindent 1) Reviewer 1 writes: "Overall the literature review is strong. I
would recommend a couple of additions. Include among them is an important work
the authors should cite on legislative size and spending and that is Gilligan
and Matsusaka's 2001 article entitled 'Fiscal Policy, Legislature Size, and
Political Parties: Evidence from the First Half of the Twentieth Century.'
Their findings are relevant for this study and should be referenced. In
addition, the recently published book \textit{Population and Politics: The
Impact of Scale} by Gerring and Veenendaal which has a comprehensive analysis
of this topic should also be incorporated into the literature review."

\vspace{.2cm}

\noindent \textbf{Response:}

\begin{quote}
We thank Reviewer 1 for these two relevant suggestions. We now cite Gilligan
and Matsusaka's 2001 article three times in our paper. We mention their article
twice in our Introduction, first on page 2: ``\textit{Larger
legislatures may reduce political particularism and increase overall government
spending, which leads to more public goods  \citep{gerring2020population,
GilliganMatsusaka2001, Weingastetal1981}}'', and then on page 4:
``\textit{The corollary of the "law of $1/n$" is that increasing legislature
size promotes excessive public spending, regardless of the partisan makeup of
the legislature \citep{GilliganMatsusaka2001}}''. We cite the article once more
in our Theory section (page 6): ``\textit{Yet, \citet{GilliganMatsusaka2001}
find that in the US legislature size is associated primarily with higher
spending on geographically concentrated benefits, such as education and
highways}.''

We now cite Gerring and Veenendaal's book four times. We mention it twice on
page 2: ``\textit{Legislature size has a significant effect on collective action
strategies, the bargaining power between state branches, government spending,
and representation \citep{crain1979cost, freire2021legislature,
gerring2020population, PrimoSnyder2008, rogers2002free, Weingastetal1981}.
However, how legislature size impacts social welfare remains less understood.
Larger legislatures may reduce political particularism and increase overall
government spending, which leads to more public goods
\citep{gerring2020population, GilliganMatsusaka2001, Weingastetal1981}}.'' We
mention it again on page 4: ``\textit{Following the seminal contribution by
\citet{Weingastetal1981}, the "law of $1/n$" posits that larger legislatures
increase the legislative pressure for providing targeted public goods to local
supporters at the expense of the entire polity \citep{freire2021legislature}.
This question has become more relevant since legislature size has increased
consistently over time \citep{gerring2020population}}.'' Finally, we also cite
the book on page 5: ``\textit{On the one hand, larger legislatures improve
representation and facilitate the electoral success of ethnic and political
minorities \citep{allenrepresentation, gerring2020population}}.''

\end{quote}

\noindent 2) Reviewer 1 writes: "In examining the relationship between
legislative size and welfare why were education and health care selected as the
independent variables? Was that decision based on data availability or were
there another basis for the decision? It is not clear in the text of the
manuscript."

\vspace{.2cm}

\noindent \textbf{Response:}

\begin{quote}

We thank Reviewer 1 for the opportunity to clarify why we have selected these
two sets of variables. We included an explanation for our decision on page 14:
"\textit{Our focus is on the impact of legislature size on education and health
care, which are the two most important public services the municipal government
should provide to citizens. According to the Brazilian Constitution,
municipalities must spend 25\% of their budget on education and 15\% on health
care. Consequently, the Ministry of Health and the Ministry of Education
provide readily available, fine-grained data on health care and education at
the municipal level, which we leverage in this study}."

\end{quote}

\noindent 3) Reviewer 1 writes: "The details of the online survey conducted of
Brazilian city councilors are lacking. What is the empirical contribution to
the study? Beyond the online format what were the other administrative details
involved with collecting that data?"

\vspace{.2cm}

\noindent \textbf{Response:}

\begin{quote}

We agree with Reviewer 1 that we needed to provide more information about our
online survey. Therefore, we have detailed our survey procedures in Section
A.14 of the Supplemental Materials (pages 23-24), and we also briefly discuss
our survey methodology on page 14 of the main article. Furthermore, we have
rewritten the second paragraph of Section 6.2 to clarify the importance of the
survey results in our paper. It now reads as follows: ``\textit{We assume that
city councilors want to extract rents and to get reelected. The rents come from
continuing in the repeated game, and the partisanship discounts that benefit.
Figure 2 shows that 65.9 percent of councilors mentioned that mayors use job
appointments to consolidate their coalition support. Moreover, 59.0 percent of
the surveyed councilors affirmed that mayors use personal favors, such as
shifting resources to places where the councilors have electoral support, to
solidify their governing coalition. This provides further evidence that mayors
do offer city councilors the benefits they demand. In this regard, granting
favors works as rent transfers for councilors. Job appointments are also
convenient for the mayors because patronage in Brazil has positive results in
terms of welfare \citep{toral2019benefits}.}''

\end{quote}

\noindent 4) Reviewer 1 writes: "The models include a dummy variable for the
northeast region. What specifically about this region would require adding it
to the model. I am generally skeptical about including such a variable
particularly since clustered standard errors are being estimated for municipal
level. Is there logical reason to control for regional effects here? Very
curious modeling decision by the authors."

\vspace{.2cm}

\noindent \textbf{Response:}

\begin{quote}

We thank Reviewer 1 for this constructive comment. The inclusion of control
variables in our model has two purposes. Firstly, the covariates improve the
consistency of our empirical results. In Section A.5 of the Appendix, we use
simulations to show that the inclusion of covariates enhances the consistency
of our RDD estimates. The simulations indicate that the controls improve
consistency even if we assume different distributions for the running variables
and for the treatment effects. Similaly, Section 5 of the manuscript
demonstrates that the covariates improve consistency in both the main estimates
and the placebo ones. Table \ref{validitycheck} (page 17, reproduced below)
shows that without controls, we would overestimate the treatment effects
(finding an increase of 1.63 legislators instead of an increase of exactly one
legislator), and underestimate the placebo treatment effects (finding a
significant decrease of 0.31 legislators where there was supposed to be no
effects in legislature size). This substantial improvement is attributed to the
addition of control variables, which make the subpopulations in each threshold
more comparable across all the thresholds. Thus, we avoid spurious comparisons
between cases on the left (right) of one threshold and those on the right
(left) of a different threshold.

\begin{table}[H] \centering 
  \caption{Research Design Validity Check (reproduction from the main paper)}
    \label{validitycheck} 
    \scalebox{0.9}{
  \begin{threeparttable}
\begin{tabularx}{\textwidth}{@{\extracolsep{\fill}}l c c c c }
\toprule
 & \multicolumn{4}{c}{\textbf{Panel A: Validity Check --- Treatment Effect on City Council Size}} \\ \cline{2-5}
   & \multicolumn{1}{c}{\small{(1)}} & 
 \multicolumn{1}{c}{\small{(2)}} & 
 \multicolumn{1}{c}{\small{(3)}} & 
 \multicolumn{1}{c}{\small{(4)}} \\

 & \multicolumn{1}{c}{\small{Additional Num.}} & 
 \multicolumn{1}{c}{\small{Placebo Add.}} & 
 \multicolumn{1}{c}{\small{Additional Num.}} & 
 \multicolumn{1}{c}{\small{Placebo Add.}} \\ 
  & \multicolumn{1}{c}{\small{Seats 2004}} & 
  \multicolumn{1}{c}{\small{Num. Seats 2004}} & 
  \multicolumn{1}{c}{\small{Seats 2004}} & 
  \multicolumn{1}{c}{\small{Num. Seats 2004}} \\
  & \multicolumn{1}{c}{\small{(Without Controls)}} & 
  \multicolumn{1}{c}{\small{(Without Controls)}} & 
  \multicolumn{1}{c}{\small{(With Controls)}} & 
  \multicolumn{1}{c}{\small{(With Controls)}} \\[1ex] \cline{2-2} \cline{3-3} \cline{4-4} \cline{5-5}
\\[-1.8ex] 
 LATE & 1.63$^{***}$ & -0.31$^{**}$ & 1.00$^{***}$ & -0.00 \\ 
  & (0.51) & (0.14) & (0.0004) & (0.0000) \\ 
\hdashline \\[-1.8ex]   
 N Left & \multicolumn{1}{c}{5184} & \multicolumn{1}{c}{4621} & \multicolumn{1}{c}{5184} & \multicolumn{1}{c}{4621} \\ 
N Right & \multicolumn{1}{c}{343} & \multicolumn{1}{c}{906} & \multicolumn{1}{c}{343} & \multicolumn{1}{c}{906} \\ 
Eff N Left & \multicolumn{1}{c}{199} & \multicolumn{1}{c}{638} & \multicolumn{1}{c}{49} & \multicolumn{1}{c}{886} \\ 
Eff N Right & \multicolumn{1}{c}{145} & \multicolumn{1}{c}{385} & \multicolumn{1}{c}{51} & \multicolumn{1}{c}{477} \\ 
BW Loc Poly & 8.717 & 6.700 & 3.008 & 8.629 \\ 
BW Bias & 13.620 & 12.114 & 5.008 & 13.466 \\ 
\bottomrule
\end{tabularx}
\end{threeparttable}}
\end{table}

Secondly, the addition of control variables also improves the efficiency of our
estimates \citep{calonico2019regression}. We add five controls to the main
specifications. We include the 2003 population because it conditions the
multiple threshold assignments. We add GDP per capita to control for Brazil's
economic expansion during the 2000s. We also add the number of seats in 2000 to
ensure that our results come from the current legislature size and not from past
seat allocations. Year was included in the models to control for seasonal
effects. Finally, we add a dummy for Northeast states. The Northeast region
received considerable attention from the federal government in the 2000s.
According to \citet{de2015politica}, in 2003 the Lula administration recreated
the Superintendency for the Development of the Northeast (SUDENE), investing BRL
84 Billion from 2003 to 2010. This amounts to around 70\% of all targeted
regional investments. One example of these investments is that the federal
government created about 100 new universities in the Northeast region during
that period. Moreover, infant mortality in the Brazilian Northeast decreased
from 22.4 deaths per 1000 infants born in 2005 to 19.6 deaths in 2008 largely
due to substantial federal investments in the region. In turn, education quality
improved from 2.69 in 2005 to a 3.14 score in 2007 (0 to 10 quality of education
score). For this reason, adding a dummy for Northeast states is essential for
ensuring the consistency and the efficiency of our estimates.

To reflect these pieces of information, we have rewritten paragraph five in
Section 5 of the manuscript (page 16). It now reads:

``[...] \textit{we add five controls to the estimates: Population in 2003; GDP
per capita; the number of seats in 2000; year; and a dummy for Northeast
municipalities. The reason for the inclusion of first variable is the multiple
threshold assignments. We add GDP per capita because wealthier cities tend to
have better public services. We include the number of seats in 2000 because
some municipalities could have experienced a change provoked by the previous
council size, thus confounding our estimates. The Northeast dummy was added to
control for the fact that the Lula administration invested heavily in the
region from 2003 until 2010, improving several development indicators
\citep{de2015politica}. We included an indicator for year to improve efficiency
and control for seasonal effects. Moreover, adding controls improves efficiency
in RDD \citep{calonico2019regression} and also enhances the consistency in the
multiple thresholds RDD.}''

We have also added a similar discussion to Section A.5 of the Supplemental
Materials.

We want to highlight further that this decision to add controls in our case is
mainly to ensure that our estimates are consistent. Even though clustered
standard errors are adequate for our purposes, they do not improve the
consistency of our estimates. In our case, the model consistency relies on
making the subpopulations comparable. That is, the subpopulation of
municipalities who have 9 and 10 legislators should be comparable with that of
of cities between 10 and 11 legislators, and so on.

\vspace{.2cm}

We would like to thank Reviewer 1 for their helpful comments and suggestions.
\end{quote}

# Reviewer 2 Comments and Responses

\noindent 1) Reviewer 2 writes: "One minor issue for the author(s) to consider
in future research: on p. 14 the paper states, "On average, municipal taxes
account for only 5\% of the local budgets, while mandatory transfers from state
and federal governments correspond to the remaining 95\%. This reduces the
ability of municipal legislators to effectively increase local spending, which
makes improvements in local services dependent only on the composition of their
local investments." There is an alternative mechanism that the author(s) has
not considered and that has been shown to work in resource allocations to
municipalities in Japan under similar circumstances. A recent paper by Amy
Catalinac, Bruce Bueno de Mesquita and Alastair Smith tests a formal model in
which variance in centrally-provided local municipality resources is a function
of a tournament among municipalities within a larger legislative district.
Perhaps future research might compare the impact of the tournament structure
with the local city council effects in Brazil as studied here."

\vspace{.2cm}

\noindent \textbf{Response:}

\begin{quote}

We agree with Reviewer 2 that testing the proposed mechanism is an exciting
project for a follow-up article. In the Discussion section (page 26), we write:
"\textit{Second, future research could evaluate whether additional legislators
help mayors gain access to federal or state transfers in countries where
resources are centrally provided, such as Japan. As suggested by
\citet{catalinac2020tournament}, in these situations the national government can
create a tournament between municipalities and provide resources to those which
offer more electoral support. Scholars might want to analyze whether this
tournament structure interacts with the mechanisms we suggest in this paper}."

\vspace{.2cm}

We would like to thank Reviewer 2 for their helpful comments and suggestions.

\end{quote}

# Reviewer 3 Comments and Responses

\noindent 1) Reviewer 3 writes: "The central story rests on some assumptions
that I would like to see justified. Do mayor's generally want to spend more,
and the city council holds them back? Why? I wonder about this assumption. Why
does increasing the size of the city council usually result in pro-mayor
additions? Under what conditions might increasing the size of the council bring
in more diverse viewpoints or more polarized policy stances? What role is
partisanship playing? It seems like it is mainly a proxy for agreement between
councilors and the mayor, but do different parties have strongly different
policy preferences? Does that matter for the results presented here?"

\vspace{.2cm}

\noindent \textbf{Response:}

\begin{quote}

We collapse two concerns from Reviewer 3 since they both speak to core topics in
our paper. In Table 6 of the Supplemental Materials (page 21), we show that an
additional legislator usually does not lead to significant increases in public
expenditure. Therefore, our results speak more about the allocation of resources
than about government spending. In our section titled "Background on the
Brazilian Case" (page 12), we clarify why increasing the city council size often
results in a pro-mayor legislator. We write (page 13): "\textit{Brazil also
adopts a unique formula to allocate seats, which combines the Hare quota and the
D’Hondt method and strongly favors larger parties \citep{nicolau2015sistemas}.
This poses a major obstacle for small parties to reach the electoral quorum, so
they often join electoral coalitions to improve their chances of winning legislative
seats \citep[68]{Ames2001}. In Brazil, mayors are usually members of the largest
coalitions \citep{poulsen2018political}, thus there is an incentive for
candidates to side with the mayor before and after the election}." We mention
that information again on page 19, footnote 3: "\textit{The effect of city
council size on the number of mayor-aligned politicians stems from the rounding
rule adopted by the proportional representation system in Brazil. The rounding
rule favors the coalitions with more votes. Most of the time, the coalition of
the elected mayor is the one that receives more votes.}" 

We did not find evidence that electing an additional legislator improves
descriptive representation in the city council. For instance, we see no
significant increase in the number of female or non-white legislators, as shown
in Table 4 (page 24). Finally, we show in the table below that the mayors'
parties are not driving our results. We have ommitted the table from the
Supplemental Materials to conserve space, but it is available on the article's
GitHub repository.

\begin{table}[!htbp] \centering 
\caption{Councilors from Major Parties} 
\label{appcouncilparty} 
\resizebox{\textwidth}{!}{
  \begin{tabular}{@{\extracolsep{\fill}}l c c c c} 
  \\[-1.8ex]\hline \\[-1.8ex] 
  & \multicolumn{1}{c}{\textbf{Councilors from PT}} & \multicolumn{1}{c}{\textbf{Councilors from PSDB}} & \multicolumn{1}{c}{\textbf{Councilors from PMDB}} & \multicolumn{1}{c}{\textbf{Councilors from PFL (DEM)}} \\ 
  \hline \\[-1.8ex] 
  LATE & -0.01 & -0.05 & -0.01 & -0.01 \\ 
  & (0.02) & (0.05) & (0.03) & (0.02) \\ 
  N Left & 5179 & 5179 & 5179 & 5179 \\ 
  N Right & 343 & 343 & 343 & 343 \\ 
  Eff N Left & 375 & 152 & 267 & 231 \\ 
  Eff N Right & 212 & 121 & 172 & 159 \\ 
  BW Loc Poly & 13.99 & 6.8 & 10.58 & 9.63 \\ 
  BW Bias & 22.64 & 11.373 & 16.803 & 15.647 \\ 
  \hline \\[-1.8ex] 
  \multicolumn{5}{l}{$^{***}$p $<$ .01; $^{**}$p $<$ .05; $^{*}$p $<$ .1} \\ 
  \end{tabular} }
\end{table}

\end{quote}

\noindent 2) Reviewer 3 writes: "Finally, I wonder about the scope conditions.
The evidence for the patterns presented from Brazil are very convincing, but
I'd like to see more discussion of why these patterns hold in Brazil and how
they might be different/ similar elsewhere."

\vspace{.2cm}

\noindent \textbf{Response:}

\begin{quote}

We entirely agree with Reviewer 3 that we needed to discuss the scope conditions
of our findings in more detail. We acknowledge that the external validity of
our results might be conditional on the contextual characteristics of our
study. We have rewritten two paragraphs in the Discussion (page 25) to highligh
the implication of our results. We write: ``\textit{Our findings have
implications that extend well beyond Brazil. A general form of our argument is
that it is easy for a politician to negotiate with members of her in-group
\citep{abbink2019, alt2018giving}. Specifically, several countries have
separate executive and legislative powers, such as the federal level of
presidential systems, state governments, and local city councils. As these
institutions are influenced by political allegiances, the dynamics we expose
here may be generalizable. Depending on legislative support, changing the
legislature size could increase the chance of electing politicians that are not
aligned with the executive, hence decreasing welfare. Despite the particular
effects on political support and welfare, the logic described in this paper
would remain relevant for empirically accessing the effect of enlarged
legislatures on welfare. Our findings may also help scholars understand why
other countries in Latin America and Asia can generate effective governance
despite having strong executives and large coalitions
\citep{pereira2012surprising}.}''

In the next paragraph (page 26), we indicate some of the limitations of our
findings and encourage scholars to conduct further research on the topic. We
write: ``\textit{This paper opens several questions for future analysis. [...]
Third, scholars might want to investigate whether our findings remain valid
under different conditions. It is possible that the mechanisms we present here
are non-linear, with additional legislators having a positive or negative
impact on welfare depending on certain electoral characteristics. Finally, it
remains unclear how other legislative features affect citizen well-being. For
example, city councils may vary in size, monetary compensation for councilors,
committee structure, and internal power structure. Understanding how
legislature size interacts with other features would improve our knowledge
about how local and national legislatures impact public services.
These questions are crucial for institution design and welfare in developing
democracies.}''

We would like to thank Reviewer 3 for their helpful comments and suggestions.
\end{quote}

\newpage
