---
title: 
to:
from: 
date: "`r Sys.time()`"
output: 
  pdf_document:
    template: article-template.latex
bibliography: references.bib 

---

We would like to thank the editor and three reviewers for their thoughtful consideration of our manuscript. We endeavored to incorporate the changes you suggested, and we believe our manuscript is much improved as a result. Below, we intersperse our reactions and revisions to the suggestions enumerated in the editor's decision letter and the three manuscript reviews. We adopt the following conventions:

\begin{itemize}
\item Suggestions identified in reviewers' reports are in \textit{italicized text}. We provide direct quotations of their reviewers' reports, lightly edited for clarifications or to conserve space.
\item Our responses to the reviewers' suggestions are in standard text.
\item The specific locations in the manuscript and online Appendix where incorporated
revisions can be found are shown in \textbf{bold text}.
\end{itemize}

\section{Suggestions Raised by Reviewer 1}
\begin{itemize}
\item \textit{Overall the literature review is strong. I would recommend a couple of additions. Include among them is an important work the authors should cite on legislative size and spending and that is \citet{GilliganMatsusaka2001} article entitled "Fiscal Policy, Legislature Size, and Political Parties: Evidence from the First Half of the Twentieth Century." Their findings are relevant for this study and should be referenced. In addition, the recently published book Population and Politics: The Impact of Scale by Gerring and Veenendaal which has a comprehensive analysis of this topic should also be incorporated into the literature review.}

\vspace{.2cm}
We thank reviewer 1 for these two relevant additions. We cite \citet{GilliganMatsusaka2001}'s article \textbf{on page 7:} "Yet, \citet{GilliganMatsusaka2001} finds that in the US legislature size is associated primarily with higher spending on geographically concentrated benefits, such as education and highways."   The Population and Politics book citation is \textbf{on page 6:} "However, legislature size does not \textit{necessarily} assure representativeness" \citep[p. 85]{gerring2020population}.

\vspace{.5cm}

\item \textit{In examining the relationship between legislative size and welfare why were education and health care selected as the independent variables? Was that decision based on data availability or were there another basis for the decision? It is not clear in the text of the manuscript.} 

\vspace{.2cm}
We thank R1 for the opportunity to clarify the selection of these two central variables for our paper. We explain our decision on \textbf{page 17}: "Access to basic education and health care are relevant goals to developing countries. For instance, according to Brazil's 1988 Constitution, municipalities have to spend 25\% of their budget on education and 15\% on health care. Consequently, the Health Ministry Data Service and the Ministry of Education Data Service provide readily available quality data on health care and education."

\vspace{.5cm}

\vspace{.2cm}
\item \textit{The details of the online survey conducted of Brazilian city councilors are lacking. What is the empirical contribution to the study? Beyond the online format what were the other administrative details involved with collecting that data?}

We agree with R1 that we needed to provide more information on the online survey. Therefore, we detailed our procedures in the \textbf{Appendix Section A.14, on pages 22-23}. We also reference it \textbf{on pages 17 and 22 (footnote 13)} in the main article.

\vspace{.5cm}

\item \textit{The models include a dummy variable for the northeast region. What specifically about this region would require adding it to the model. I am generally skeptical about including such a variable particularly since clustered standard errors are being estimated for municipal level. Is there logical reason to control for regional effects here? Very curious modeling decision by the authors.}

\vspace{.2cm}
\textbf{FALTA FAZER: Dummy para a região Nordeste: estimar os modelos sem a dummy e reportar este resultado no artigo. Corrigir as menções aos coeficientes caso eles mudem. Colocar as regressões com a dummy no apêndice.}

\vspace{.5cm}

\end{itemize}
\section{Suggestions Raised by Reviewer 2}
\begin{itemize}
\item \textit{One minor issue for the author(s) to consider in future research: on p. 14 the paper states, "On average, municipal taxes account for only 5\% of the local budgets, while mandatory transfers from state and federal governments correspond to the remaining 95\%. This reduces the ability of municipal legislators to effectively increase local spending, which makes improvements in local services dependent only on the composition of their local investments." There is an alternative mechanism that the author(s) has not considered and that has been shown to work in resource allocations to municipalities in Japan under similar circumstances. A recent paper by \citet{catalinac2020tournament} tests a formal model in which variance in centrally-provided local municipality resources is a function of a tournament among municipalities within a larger legislative district. Perhaps future research might compare the impact of the tournament structure with the local city council effects in Brazil as studied here.}

\vspace{.2cm}
We agree with R2 that testing the proposed mechanism is an extremely exciting project for a follow-up article. In our \textbf{conclusion, on page 29,} we write: "Future research should also evaluate whether an extra-legislator is helping the mayor in her competition for state or federal transfers, as proposed by \citet{catalinac2020tournament}."

\vspace{.5cm}

\end{itemize}
\section{Suggestions Raised by Reviewer 3}
\begin{itemize}
\item \textit{The central story rests on some assumptions that I would like to see justified. Do mayor's generally want to spend more, and the city council holds them back? Why? I wonder about this assumption. Why does increasing the size of the city council usually result in pro-mayor additions? Under what conditions might increasing the size of the council bring in more diverse viewpoints or more polarized policy stances? What role is partisanship playing? It seems like it is mainly a proxy for agreement between councilors and the mayor, but do different parties have strongly different policy preferences? Does that matter for the results presented here?}

\vspace{.2cm}
\textbf{FALTA COMPLETAR:} We collapse two paragraphs from R3 since they speak to core topics in our paper. \textbf{In the Appendix Table XXX, on page XXX,} we show that an extra-legislator usually does not increase the municipal spending significantly. Therefore, our results speak more about the allocation of resources than on public spending. \textbf{On page 15, in the Background on the Brazilian Case Section,} we clarify why increasing the city council size usually results in a pro-mayor legislator. "Additionally, Brazil's formula for apportioning legislative seats (a combination of the Hara quota and the D'Hondt method) is an obstacle to small parties or coalitions attaining the electoral quotient that might give them a legislative seat. As a result, they often ally with larger coalitions so that they can reach the electoral quotient \citep[p. 68]{Ames2001}. Being a central political figure in the municipality, often the mayor is also a member of the most voted coalition." See also \textbf{footnote 12, on page 21-22.} Unfortunately, we could not find evidence that an extra-legislator improves descriptive representation in the city council, for instance, more female or non-white legislators \textbf{(see Table 4).} Finally, \textbf{in the Appendix, on page XX,} we show that the mayors' party is not driving the results. 

\vspace{.5cm}

\item \textit{I wonder about the scope conditions. The evidence for the patterns presented from Brazil are very convincing, but I'd like to see more discussion of why these patterns hold in Brazil and how they might be different/ similar elsewhere.}

\vspace{.2cm}
We acknowledge that the external validity of our findings might be conditional on the contextual characteristics of our study. \textbf{On page 6-7,} we acknowledge that "since the seminal paper by \citet{Weingastetal1981}, 30 papers have systematically tested the effects of legislature size on government spending. Of these papers, only \citet{lewis2019legislature} investigates its effects on welfare, showing that larger legislatures have a negative welfare effect. \citet{frey2021legislature} analyses the Brazilian case after the 2009 legislature size change and finds a null effect in service provision from 2012 to 2016. Yet, \citet{GilliganMatsusaka2001} finds that in the US legislature size is associated primarily with higher spending on geographically concentrated benefits, such as education and highways. These results suggest that the legislature size and welfare nexus needs a dedicated theoretical and empirical assessment."
Additionally, \textbf{in the Discussion Section, on page 29,} we write about the implications of our findings beyond Brazil. In this paragraph, we added the following new sentence: "As a caveat, our results might not be externally valid under different institutional norms (e.g., election rules or methods to allocating legislative seats) or at other governmental levels (federal or state). The findings presented here might also not be linear, since the impact of an extra-legislator should be heterogeneous depending upon the size of different legislatures or jurisdictions."

\vspace{.5cm}


\end{itemize}


